{% set name = "iucn_sim" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/tobiashofmann88/iucn_extinction_simulator/archive/v{{ version }}.tar.gz
  sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas
    - numpy

test:
  imports:
    - iucn_sim
  commands:
    - iucn_sim --version

about:
  home: https://github.com/tobiashofmann88/iucn_extinction_simulator
  license: MIT
  license_family: LICENSE
  summary: 'Estimate extinction probabilities and dates for a given set of species, based on IUCN threat assessments'


